// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC05m2Mlwep_9za1mYRqOjNM8OFn1Cels',
    appId: '1:554007908629:web:0b3cc9a38a58601495191c',
    messagingSenderId: '554007908629',
    projectId: 'trainee-e4218',
    authDomain: 'trainee-e4218.firebaseapp.com',
    storageBucket: 'trainee-e4218.appspot.com',
    measurementId: 'G-L00VJQXWS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJSFhtx5prmRNc5K51srT288QcZk34V7Y',
    appId: '1:554007908629:android:6ae86cb73650d2c695191c',
    messagingSenderId: '554007908629',
    projectId: 'trainee-e4218',
    storageBucket: 'trainee-e4218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADOR682Ux1coyUOIsH9mZ3zlcAqpk-qNM',
    appId: '1:554007908629:ios:1ebf22a060c013e095191c',
    messagingSenderId: '554007908629',
    projectId: 'trainee-e4218',
    storageBucket: 'trainee-e4218.appspot.com',
    iosBundleId: 'com.example.traineeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADOR682Ux1coyUOIsH9mZ3zlcAqpk-qNM',
    appId: '1:554007908629:ios:c773bdd70d69299295191c',
    messagingSenderId: '554007908629',
    projectId: 'trainee-e4218',
    storageBucket: 'trainee-e4218.appspot.com',
    iosBundleId: 'com.example.traineeApp.RunnerTests',
  );
}
